# Generated by Django 4.0.4 on 2022-04-29 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sazan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[['Макуха', 'Макуха'], ['Флет метод', 'Флет метод'], ['Цоколь', 'Цоколь'], ['Блесна', 'Блесна'], ['Пикер', 'Пикер'], ['Универсал', 'Универсал'], ['резинка', 'резинка']], max_length=100, null=True, verbose_name='Cазан')),
                ('sum', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество рыбы')),
                ('kg', models.FloatField(blank=True, null=True, verbose_name='Вес в кг')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('description', models.CharField(blank=True, default='ноль', max_length=500, null=True, verbose_name='Краткое описание')),
                ('fish_name', models.CharField(blank=True, default='ноль', max_length=500, null=True, verbose_name='Кого поймали')),
                ('fish_sum', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество рыбы в шт.')),
                ('fish_kg', models.FloatField(blank=True, default=0, null=True, verbose_name='Общий вес в кг')),
                ('vodka', models.FloatField(blank=True, default=0, null=True, verbose_name='Количество распитой водочки')),
                ('beer', models.FloatField(blank=True, default=0, null=True, verbose_name='Количество распитого пивка')),
                ('prikorm', models.FloatField(blank=True, default=0, null=True, verbose_name='Количество прикорма')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место ловли')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('phase', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, default='karp.jpg', null=True, upload_to='', verbose_name='Аватар')),
                ('gender', models.CharField(choices=[['Не определено', 'Не определено'], ['макушатник', 'макушатник'], ['спининг', 'спининг'], ['фидер', 'фидер'], ['поплавочка', 'поплавочка'], ['багрильщик', 'багрильщик']], default='нет', max_length=15, null=True, verbose_name='Предпочитаемый вид ловли')),
                ('relationship', models.CharField(choices=[['Макуха', 'Макуха'], ['Флет метод', 'Флет метод'], ['Цоколь', 'Цоколь'], ['Блесна', 'Блесна'], ['Пикер', 'Пикер'], ['Универсал', 'Универсал'], ['резинка', 'резинка']], default='нет', max_length=30, null=True, verbose_name='Cпециализация')),
                ('karas', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество пойманных карасей')),
                ('sazan', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество пойманных сазанов')),
                ('lech', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество пойманных лещей')),
                ('other_fish', models.IntegerField(blank=True, default=0, null=True, verbose_name='Прочая рыба')),
                ('fish_sum', models.PositiveIntegerField(blank=True, max_length=25, null=True, verbose_name='Количество пойманной рыбы')),
                ('fish_kg', models.FloatField(blank=True, max_length=25, null=True, verbose_name='Общий вес в кг')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
